import Head from 'next/head';
import Footer from '../components/Footer';
import NavBar from '../components/NavBar';
import {useEffect} from 'react';
import RumahRefi from './RumahRefi';

export default function Home () {
  return (
    <div className="w-full">
      <Head>
        <title>Refi Nurifani Putri</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <NavBar />
      <div>
        <RumahRefi />
      </div>
      <Footer />
    </div>
  );
}
